### ISSUE TITLE
npm package deployment

### ISSUE THREAD

**Issue by bmingles** [slate-solid/slate-solid#13]
Need to deploy @slate-solid/core to npm and make sure it can be installed.

**Resources**
- https://vite.dev/guide/build#library-mode
- https://github.com/solidjs/vite-plugin-solid/issues/97

Note I tested a minimal production vite config that seems promising. I've only tested via npm link, and still have to figure out building the types.

```typescript
{
  build: {
    target: 'esnext',
    lib: {
      entry: resolve(__dirname, 'src/index.ts'),
      formats: ['es'],
      name: 'SlateSolidCore',
      fileName: 'index',
    },
    rollupOptions: { external: ['solid-js'] },
  }
}
```

Also, this config bundles everything into single file. May not be optimal for tree shaking, but need to investigate.

**Comment by bmingles** [comment]
I dug into the root cause of [Uncaught Error: The useSlate hook must be used inside the <Slate> component's context. #79](https://github.com/slate-solid/slate-solid/issues/79) a bit.
- I can reproduce by installing @slate-solid/core locally from npm
- Comparing the output of working vs not working, it seems the library is missing component registry calls for the components exported by the library. e.g. `export const Slate = _$$component(_REGISTRY, "Slate", (origProps) => {`
- Minimal testing with vite production library-mode would suggest this is a build issue (possible there's a way to configure the consumer to wrap things, but seems better for the library to be standalone and include the registrations)

**Comment by Noobulater** [comment]
If it's a vite issue, we should try to resolve, I feel it's become the new defact-o webpack and probably close to the new standard if not already. 

Selfishly I also use it.

**Comment by bmingles** [comment]
It seems that simply renaming the root `index.ts` -> `index.tsx` and updating the solid exports condition fixed this. The vite config experiment I did is worth keeping in mind if we ever want to tweak this, but seems better not to bundle the components if we don't have to.

**Comment by bmingles** [comment]
@Noobulater I think this is fixed now. Should be able to use latest https://www.npmjs.com/package/@slate-solid/core/v/1.0.13 in a Vite project without issue.
