### ISSUE TITLE
Huge Document Performance

### ISSUE THREAD

**Issue by bmingles** [slate-solid/slate-solid#15]
The huge document example is a bit sluggish. Probably a more systemic issue that needs to be investigated.

**Comment by Noobulater** [comment]
So I spent some time poking around, I *think* the whole document might be repainting when a change is made, and have a hunch that maybe virtual dom libraries like react batch updates for the next frame before repainting.

I'm wondering what you think of this. Also disclaimer I might be out of my depth on this, it goes deeper into the library than I anticipated. 

![image](https://github.com/user-attachments/assets/5abb20c8-2f9a-4e14-9a00-7da1bce27ff9)

**Comment by bmingles** [comment]
I don't have a lot of experience with the profiler. Would have to probably look at it interactively to dig in. One thing that does stand out to me is `HMRComp` which I'm assuming would be a dev only thing related to hot module reloading. Is this in dev build? If so we may need to profile in a prod build to rule out any dev tooling overhead.

**Comment by bmingles** [comment]
@Noobulater good call on the re-rendering thing. Looks like this may also be the underlying cause of [Placeholder doesn’t return on ios #11](https://github.com/slate-solid/slate-solid/issues/11). Flashing DOM elements in Chrome would suggest all children are getting re-rendered even when changing selection.

![re-render](https://github.com/user-attachments/assets/848b9abb-98bb-4af2-ac78-3e51edef5628)

Now to dig in to see what it will take to fix it.

**Comment by bmingles** [comment]
So far it looks like the issue may be that every component is responding to a subscription to the editor instance instead of more granular subscriptions to the node of interest. The editor node never actually changes reference, so I had to put it in a signal that always triggers when the editor is set. It may be this is a side effect of that, but I'm hoping there's a way to get child components to only react to respective node changes. I tried setting some logging effects in Children component to see if I could get some nodes to not respond but so far not working. Will keep digging.

**Comment by bmingles** [comment]
@Noobulater 
I've made some optimizations, and this is looking much better to me.
- Selection no longer causes every element to change
- I added better memoization in a few places, and this seems to have caught the bigger culprits

If you get a chance to test in a production build (should be able to use the deployed GH site) https://slate-solid.github.io/slate-solid/huge-document , I'd be curious to see how it performs for you.

**Comment by Noobulater** [comment]
@bmingles Great work! I did some brief testing but marked improvement

**Comment by Noobulater** [comment]
Did some more testing this morning and it's looking good. I'm happy to sign off on it

**Comment by bmingles** [comment]
@Noobulater let me know if you have any more testing you want to do on this one. Things seem to be performing well to me now.

**Comment by Noobulater** [comment]
I'm all set if you are 👍

**Comment by bmingles** [comment]
Great. Closing
