### ISSUE TITLE
Embedded and Void elements re-rendering on selection change

### ISSUE THREAD

**Issue by Noobulater** [slate-solid/slate-solid#30]
### Observed Behavior
When making changes to the document, selection and otherwise, embedded and I'm assuming all void elements will be removed and recreated.

### Expected Behavior
When making changes to the document, only affected blocks and text should be changed and repainted.

### OS / Platforms 
Windows 11 / Edge

https://github.com/user-attachments/assets/01117003-d814-47fd-95de-7e1c95777fa3

**Comment by bmingles** [comment]
I think the issue with embedded has been fixed. I'm seeing a different [issue with editable voids](slate-solid/slate-solid/issues/45), but I don't think it's the same thing.

**Comment by bmingles** [comment]
@Noobulater whenever you get a chance, can you see if you are still observing this issue?

**Comment by Noobulater** [comment]
No longer observing this issue
