### ISSUE TITLE
Editable - Implement remaining event handlers

### ISSUE THREAD

**Issue by bmingles** [slate-solid/slate-solid#4]
Editable - Implement remaining event handlers.

**Comment by Noobulater** [comment]
Here are the event handlers present in `slate-react`'s `Editable` component but missing in `slate-solid`:

- `onCopy`
- `onCut`
- `onPaste`
- `onDragStart`
- `onDrop`
- `onSelect`
- `onCompositionStart`
- `onCompositionEnd`
- `onCompositionUpdate`

These handlers could be added to `slate-solid` for more complete functionality.
